moviewebsite/credentials/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'credentials'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
]

moviewebsite/movieapp/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'movieapp'
urlpatterns = [
    path('',views.allMovieCat,name='home'),
    path('<slug:c_slug>/',views.allMovieCat,name='movie_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.movieDetail,name='movieCatDetail'),
    path('movies',views.movieadd,name='movieadd'),
    path('<slug:c_slug>/<slug:product_slug>/delete',views.delete,name='delete'),
    path('<slug:c_slug>/<slug:product_slug>/update',views.update,name='update'),
    path('search', views.search, name='search'),
    path('profile', views.profile, name='profile'),
]

moviewebsite/moviewebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('credentials/', include('credentials.urls')),
    path('', include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root = settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root = settings.MEDIA_ROOT)

moviewebsite/credentials/models.py
from django.db import models

# Create your models here.

moviewebsite/movieapp/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category',blank=True)
    link = models.CharField(max_length=1000,default=False)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('movieapp:movie_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Movie(models.Model):

    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product',blank=True)
    release_date = models.DateField()
    actors = models.CharField(max_length=250)
    ytlink = models.CharField(max_length=1000)
    username = models.CharField(max_length=250,default=False)

    def get_url(self):
        return reverse('movieapp:movieCatDetail',args=[self.category.slug,self.slug])
    def get_url_p(self):
        return reverse('movieapp:movie_by_category',args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

moviewebsite/movieapp/forms.py
from django import forms
from django.db import models
from . models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name','description','release_date','image']

moviewebsite/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        if User.objects.filter(username=username).exists():
            messages.info(request,"Username already exist")
            return redirect('credentials:register')
        elif User.objects.filter(email=email).exists():
            messages.info(request,"Email already Taken")
            return redirect('credentials:register')
        else:
            user = User.objects.create_user(username=username,password=password,first_name=first_name,last_name=last_name,email=email)

            user.save();
            print("user created")
        return redirect('credentials:login')

    return render(request, "register.html")

def login(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('movieapp:home')
        else:
            messages.info(request,"Incorrect Username or Password")
            return redirect('credentials:login')
    return render(request,"login.html")
def logout(request):
    auth.logout(request)
    return redirect('movieapp:home')

moviewebsite/movieapp/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from django.utils.text import slugify

from . forms import MovieForm
from . models import Category,Movie
# Create your views here.

def allMovieCat(request,c_slug=None):
    c_page = None
    products_list = None
    if c_slug!=None:
        c_page = get_object_or_404(Category,slug = c_slug)
        products_list = Movie.objects.all().filter(category = c_page)
    else:
        products_list = Movie.objects.all()
    paginator = Paginator(products_list,8)
    try:
        page = int(request.GET.get('page','1'))
    except :
        page = 1
    try:
        products = paginator.page(page)
    except ( EmptyPage,InvalidPage ):
        products = paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})

def movieDetail(request,c_slug,product_slug):
    try:
        product = Movie.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e

    return render(request,'movie.html',{'product':product})

def movieadd(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    if request.method =='POST':
        username = request.POST['username']
        moviename = request.POST['name']
        category_id = request.POST.get('category')
        category = Category.objects.get(pk=category_id)
        actors = request.POST['actors']
        desc = request.POST['description']
        img = request.FILES['image']
        date = request.POST['date']
        ytlink = request.POST['ytlink']
        slug = slugify(moviename)

        mov = Movie(username=username,name=moviename,description=desc,category=category,image=img,release_date=date,actors=actors,ytlink=ytlink,slug=slug)
        mov.save()
        return redirect('/')
    return render(request,'addmovie.html',context)

def delete(request, c_slug, product_slug):
    movie = get_object_or_404(Movie, category__slug=c_slug, slug=product_slug)
    movie.delete()
    return redirect('movieapp:home')
    # return render(request, 'movie.html')

def update(request,product_slug,c_slug):
    movie = get_object_or_404(Movie, category__slug=c_slug, slug=product_slug)
    form = MovieForm(request.POST or None, request.FILES,instance=movie)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('movieapp:home')
    return render(request,'edit.html',{'form':form,'movie':movie})

def search(request):
    products = None
    query = None

    try:
        if 'q' in request.GET:
            query = request.GET.get('q')
            if query != "":
                products = Movie.objects.filter(Q(name__icontains=query) | Q(description__icontains=query) | Q(category__name__icontains=query))
    except Exception as e:
        # Handle the exception (e.g., log it or render an error page)
        print(f"An error occurred: {e}")
        products = None  # Set products to None to indicate an error

    return render(request, 'search.html', {'query': query, 'products': products})


def profile(request):
    if request.method =='POST':
        user = request.user
        user.username = request.POST.get('username','')
        user.first_name = request.POST.get('f_name', '')
        user.last_name = request.POST.get('l_name', '')
        user.email = request.POST.get('email', '')
        user.save()
        return redirect('movieapp:home')
    return render(request,'profile.html')

moviewebsite/templates/category.html
{% load static %}
<head>
<title>{% if category %}
        {{ category.name }} - XPAIN Movie
    {% else %}
       See our New Collections - Xpain Movie
    {% endif %}</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Travello template project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
<link rel="stylesheet" href="{% static 'css/movie.css' %}">
<link rel="stylesheet" href="{% static 'css/eachmovie.css' %}">
</head>

{#{% block title %}#}
{##}
{#{% endblock %}#}

{% block content %}
    <nav class="navbar navbar-expand-lg" style="padding: 20px;color: white">
  <a class="navbar-brand" style="font-weight: bold;font-size: 20px">Xpain movies</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'movieapp:home' %}" style="color: white">Home <span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_authenticated %}
          <li class="nav-link" style="color: red;font-size: 14px"><a href="{% url 'movieapp:profile' %}" style="text-decoration: none;color: red">{{ user.username }}</a></li>
            <li class="nav-link"><a href="{% url 'credentials:logout' %}" style="text-decoration: none;color: white">Logout</a></li>
        {% else %}
            <li class="nav-link"><a href="{% url 'credentials:register' %}" style="text-decoration: none;color: white">Register</a></li>
            <li class="nav-link"><a href="{% url 'credentials:login' %}" style="text-decoration: none;color: white">Login</a></li>
        {% endif %}
      <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: white">
            Movies
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a href="{% url 'movieapp:home' %}" class="dropdown-item">All Movies</a></li>
            <li>{% for link in links %}
            <li><a href="{{ link.get_url }}" class="dropdown-item">{{ link.name }}</a>
            {% endfor %}</li>
          </ul>
        </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'movieapp:search' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <a href="" style="text-decoration: none;color: white;"><button class="btn btn-outline-success my-2 my-sm-0" type="submit" >Search</button></a>
    </form>
      <a href="{% url 'movieapp:movieadd' %}"><button class="btn btn-secondary" style="margin-left: 10px;">Add movies</button></a>
  </div>
</nav>
    {% if category %}
        <div>
            <div class="row my_row_class">
                <div class="mx-auto">
                <p><a class="btn btn-outline-warning" href="{% url 'movieapp:home' %}">Our Movie Collections >></a> </p>
            </div>
            </div>
        </div>
    {% endif %}
    <div class="">
        {% if category %}

            <div class="top">
                <div class="columns">
                    <div class="column is-full featured_wrapper p-0">
                        <img src="{{ category.image.url }}" class="featured">
                        <div class="title_wrapper">
                            <span class="has-text-white">Trending Today</span>
                            <h1 class="title is-1 has-text-white" style="font-weight: bold;font-size: 38px">{{ category.description | truncatewords:5}}</h1>
                            <a href="{{ category.link }}"><button class="button is-medium">Watch It Now</button></a>
                        </div>
                    </div>
                </div>
            </div><br>
        {% else %}
            <br>
            <div>
            <img class="my_image my_image_padding" src="{% static 'img/pexels-tima-miroshnichenko-7991532.jpg' %}" alt="our products" height="400px" width="1200px">
            </div>

        {% endif %}
    <div>
        <div>
        <br>
        <div class="container">
            <div class="row mx_auto">
            {% for prod in products.object_list %}
{#                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">#}
{#                    <div class="card text-center" style="min-width: 10rem;  margin-bottom: 15px">#}
{#                        <a href="{{ prod.get_url }}"><img src="{{ prod.image.url }}" alt="{{ prod.name }}" style="height: 200px;object-fit: cover" class="card-img-top my_image"> </a>#}
{#                    <div class="card-body">#}
{##}
{#                        <h4>{{ prod.name }}</h4>#}
{#                        <p>{{ prod.category }}</p>#}
{#                    </div>#}
{#                    </div>#}
{#                </div>#}
                <div class="movie_card" id="bright" style="width: 650px;height: 420px; background: url('{{ prod.image.url }}') no-repeat; background-size: 630px; background-position:center right; ">
                  <div class="info_section">
                    <div class="movie_header">
                        <div style="display: block">
                        <a href="{{ prod.get_url }}"><img class="locandina" src="{{ prod.image.url }}" /></a>
                            </div>
                    <br>

                      <h1>{{ prod.name }}</h1>
                      <h4>{{ prod.actors }}</h4>


                      <p class="type">{{ prod.category }}</p>
                        <br>
                        <a href="{{ prod.ytlink }}"><button class="button is-medium">Watch It Now</button></a>
                    <br>
                    <br>
                        {% if prod.username == user.username  %}
                            <a><button class="button is-medium" style="background: lightgreen">Delete</button></a>
                        {% endif %}
                    </div>
                  </div>
                    </div>

            {% endfor %}
        </div>
        <br><br><br>
        <div class="mx-auto">

            {% if products.paginator.num_pages > 1 %}

            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                    <a href="?page={{ pg }}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{ pg }}</a>
                {% endfor %}
            </div>
        {% endif %}
        </div>
        <br>
        </div>
        </div>
    </div>
    </div>
    <br><br>
{% endblock %}

moviewebsite/templates/movie.html
{% load static %}
<head>
{% block title %}
    {% if category %}
        {{ product.name }} - XPAIN SHOPPE
    {% endif %}
{% endblock %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <link rel="stylesheet" href="{% static 'css/eachmovie.css' %}">
{#<link rel="stylesheet" href="{% static 'css/movie.css' %}">#}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<style>
    body{
        background-image: url("{{ product.image.url }}");
        background-size: cover;
        overflow: hidden;
        backdrop-filter: opacity(0.5);
        backdrop-filter: brightness(30%);

    }
    button {
	background: #f40612 !important;
	color: #fff !important;
	font-size: 18px;
	padding: 0.5rem 3rem;
	outline: none;
	border: 0 !important;
}
</style>
</head>
{% block content %}
    <nav class="navbar navbar-expand-lg" style="padding: 20px;color: white">
  <a class="navbar-brand" style="font-weight: bold;font-size: 20px;color: revert">Xpain movies</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'movieapp:home' %}" style="color: white">Home <span class="sr-only"></span></a>
      </li>
      {% if user.is_authenticated %}
          <li class="nav-link" style="color: red;font-size: 14px"><a href="{% url 'movieapp:profile' %}" style="text-decoration: none;color: red">{{ user.username }}</a></li>
            <li class="nav-link"><a href="{% url 'credentials:logout' %}" style="text-decoration: none;color: white">Logout</a></li>
        {% else %}
            <li class="nav-link"><a href="{% url 'credentials:register' %}" style="text-decoration: none;color: white">Register</a></li>
            <li class="nav-link"><a href="{% url 'credentials:login' %}" style="text-decoration: none;color: white">Login</a></li>
        {% endif %}
      <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: white">
            Movies
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a href="{% url 'movieapp:home' %}" class="dropdown-item">All Movies</a></li>
            <li>{% for link in links %}
            <li><a href="{{ link.get_url }}" class="dropdown-item">{{ link.name }}</a>
            {% endfor %}</li>
          </ul>
        </li>
    </ul>

  </div>
</nav>
    <div class="row my_prod_row_class" style="padding: 20px">
{#        <div class="mx-auto" style="text-align: end">#}
{#            <p><a href="{% url 'movieapp:home' %}" style="text-decoration: none;font-size: 14px">HOME</a> | <a href="{% url 'movieapp:movie_by_category' product.category.slug %}" style="text-decoration: none;font-size: 14px" >{{ product.category }}</a>  </p>#}
{#        </div>#}
    <div class="container">
    <br>
{#    <div class="row">#}
{#        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">#}
{#            <div style="min-width: 18rem">#}
{#                <img src="{{ product.image.url }}" alt="{{ product.name }}" width="300px" height="300px" style="object-fit: contain">#}
{#            </div>#}
{#    </div>#}
{#            <div class="col-12 col-sm-12 col-md-12 col-lg-6 ">#}
{#            <div>#}
{#                <h1 class="my_prod_title">{{ product.name }}</h1>#}
{#                <p>${{ product.price }}</p>#}
{#                <p style="font-size: 20px;font-weight: bold" >Product Description</p>#}
{#                <p>{{ product.description }}</p>#}
{#    </div>#}
{#            </div>#}
{#        </div>#}
<div class="movie_card" id="bright" style="width: 1000px;align-items: center;height: max-content;margin: auto; justify-content: center">
  <div class="info_section">
    <div class="movie_header">
      <img class="locandina" src="{{ product.image.url }}" />
      <h1>{{ product.name }}</h1>
      <h4>{{ product.actors }}</h4>
      <h5 class="type">{{ product.category }}</h5>
    </div>
    <div class="movie_desc">
      <p class="text">
        {{ product.description }}
      </p>

      <br>
        <a href="{{ product.ytlink }}"><button class="button is-medium">Watch It Now</button></a>
    <br>
    <br>
        {% if product.username == user.username  %}
            <form method="post">
                {% csrf_token %}
               <button type="submit" class="button is-medium" style="background: lightgreen"> <a href="{% url 'movieapp:delete' product.category.slug product.slug %}" style="text-decoration: none;color: white">Delete</a></button><br><br>

                </form>
             <a href="{% url 'movieapp:update' product.category.slug product.slug %}"><button class="button is-medium" style="background: lightgreen">Update</button></a>
        {% endif %}
  </div>
  </div>
    </div>
    </div>
{% endblock %}

moviewebsite/templates/movie1.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/movie.css' %}">
</head>
<div class="top">
	<div class="columns">
		<div class="column is-full featured_wrapper p-0">
			<img src="{{ product.image.url }}" class="featured">
			<div class="title_wrapper">
				<span class="has-text-white">Trending Today</span>
				<h1 class="title is-1 has-text-white">The Untold Story of the great Lorem Ipsum</h1>
				<button class="button is-medium">Watch It Now</button>
			</div>
		</div>
	</div>
</div>
<div class="container text-center" >
	<div class="columns is-multiline p-0 pt-6 last">
		<div class="column is-full">
			<p class="has-text-white">Action Movies Collection</p>
		</div>
		<div class="column is-one-quarter text-center">
			<img src="{{ product.image.url }}" style="height: 100px;width: 100px">
		</div>
	</div>
	</div>
</div>

moviewebsite/templates/search.html
{% load static %}
<head>
{% block title %}
    {% if category %}
        {{ product.name }} - XPAIN SHOPPE
    {% endif %}
{% endblock %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <link rel="stylesheet" href="{% static 'css/eachmovie.css' %}">
{#<link rel="stylesheet" href="{% static 'css/movie.css' %}">#}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<style>
    body{
        background-image: url("{% static 'img/movie_bg.jpg' %}");
        background-size: cover;
        backdrop-filter: opacity(0.5);
        backdrop-filter: brightness(30%);

    }
    button {
	background: #f40612 !important;
	color: #fff !important;
	font-size: 18px;
	padding: 0.5rem 3rem;
	outline: none;
	border: 0 !important;
}
</style>
</head>
{% block content %}
    <nav class="navbar navbar-expand-lg" style="padding: 20px;color: white">
  <a class="navbar-brand" style="font-weight: bold;font-size: 20px;color: revert">Xpain movies</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'movieapp:home' %}" style="color: white">Home <span class="sr-only"></span></a>
      </li>
      {% if user.is_authenticated %}
          <a href="{% url 'movieapp:profile' %}" style="text-decoration: none;color: red" ><li class="nav-link" style="color: red;font-size: 14px">{{ user.username }}</li></a>
            <li class="nav-link"><a href="{% url 'credentials:logout' %}" style="text-decoration: none;color: white">Logout</a></li>
        {% else %}
            <li class="nav-link"><a href="{% url 'credentials:register' %}" style="text-decoration: none;color: white">Register</a></li>
            <li class="nav-link"><a href="{% url 'credentials:login' %}" style="text-decoration: none;color: white">Login</a></li>
        {% endif %}
      <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: white">
            Movies
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a href="{% url 'movieapp:home' %}" class="dropdown-item">All Movies</a></li>
            <li>{% for link in links %}
            <li><a href="{{ link.get_url }}" class="dropdown-item">{{ link.name }}</a>
            {% endfor %}</li>
          </ul>
        </li>
    </ul>

  </div>
</nav>
    <div class="row my_prod_row_class" style="padding: 20px">
{#        <div class="mx-auto" style="text-align: end">#}
{#            <p><a href="{% url 'movieapp:home' %}" style="text-decoration: none;font-size: 14px">HOME</a> | <a href="{% url 'movieapp:movie_by_category' product.category.slug %}" style="text-decoration: none;font-size: 14px" >{{ product.category }}</a>  </p>#}
{#        </div>#}
    <div class="container">
    <br>
{#    <div class="row">#}
{#        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">#}
{#            <div style="min-width: 18rem">#}
{#                <img src="{{ product.image.url }}" alt="{{ product.name }}" width="300px" height="300px" style="object-fit: contain">#}
{#            </div>#}
{#    </div>#}
{#            <div class="col-12 col-sm-12 col-md-12 col-lg-6 ">#}
{#            <div>#}
{#                <h1 class="my_prod_title">{{ product.name }}</h1>#}
{#                <p>${{ product.price }}</p>#}
{#                <p style="font-size: 20px;font-weight: bold" >Product Description</p>#}
{#                <p>{{ product.description }}</p>#}
{#    </div>#}
{#            </div>#}
{#        </div>#}
    <p class="text-center my_search_text" style="color: white;">You have searcher for : <b style="color: red;"><strong>{{ query }}</strong></b></p>
    {% for prod in products %}
<div class="movie_card" id="bright" style="width: 1000px;align-items: center;height: max-content;margin: auto; justify-content: center">
  <div class="info_section">
    <div class="movie_header">
      <img class="locandina" src="{{ prod.image.url }}" />
      <h1>{{ prod.name }}</h1>
      <h4>{{ prod.category }}</h4>
      <p class="type">{{ prod.actors }}</p>
    </div>
    <div class="movie_desc">
      <p class="text">
        {{ prod.description }}
      </p>

      <br>
        <a href="{{ prod.ytlink }}"><button class="button is-medium">Watch It Now</button></a>
    <br>
    <br>
  </div>
  </div>
    </div>
        <br>
        {% endfor %}
    </div>
{% endblock %}